# Generated by Django 4.2.4 on 2023-09-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='full_name',
        ),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='student',
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GuardianContact',
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ManyToManyField(related_name='guardians', to='user_management.student'),
        ),
    ]
