# Generated by Django 4.2.4 on 2023-08-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
        ('user_management', '0002_alter_teacher_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='school_management.classroom'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_management.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='user_management.guardian'),
        ),
    ]
