# Generated by Django 4.2.4 on 2023-08-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
        ('user_management', '0003_alter_enrolment_classroom_alter_enrolment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
            preserve_default=False,
        ),
    ]
