# Generated by Django 4.2.4 on 2023-09-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_guardian_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='student',
            new_name='students',
        ),
    ]
