# Generated by Django 4.2.4 on 2023-08-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_student_guardian_guardian_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='user_management.student'),
        ),
    ]
