# Generated by Django 4.2.4 on 2023-09-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_student_guardian_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='students',
            field=models.ManyToManyField(to='user_management.student'),
        ),
    ]
