# Generated by Django 4.2.4 on 2024-04-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('school_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='sites.site'),
            preserve_default=False,
        ),
    ]
