# Generated by Django 4.2.4 on 2023-08-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='school',
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_management.school'),
            preserve_default=False,
        ),
    ]
