# Generated by Django 4.2.4 on 2023-08-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum_management', '0004_exam_alter_syllabus_options_alter_exercise_taken_by_and_more'),
        ('user_management', '0003_alter_enrolment_classroom_alter_enrolment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student')),
                ('subjects', models.ManyToManyField(to='curriculum_management.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
