# Generated by Django 4.2.4 on 2024-04-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('curriculum_management', '0003_initial'),
        ('report_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='subjects',
            field=models.ManyToManyField(to='curriculum_management.subject'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher'),
        ),
        migrations.AddField(
            model_name='studentreport',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.term'),
        ),
    ]
