# Generated by Django 4.2.4 on 2023-08-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_management', '0001_initial'),
        ('exam_management', '0001_initial'),
        ('user_management', '0001_initial'),
        ('curriculum_management', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='subjects',
            field=models.ManyToManyField(to='curriculum_management.subject'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.term'),
        ),
        migrations.AddField(
            model_name='examseating',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam'),
        ),
        migrations.AddField(
            model_name='examseating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.level'),
        ),
        migrations.AddField(
            model_name='exam',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='taken_by',
            field=models.ManyToManyField(through='exam_management.ExamSeating', to='user_management.student'),
        ),
    ]
