# Generated by Django 4.2.4 on 2023-08-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0003_alter_enrolment_classroom_alter_enrolment_student_and_more'),
        ('curriculum_management', '0004_exam_alter_syllabus_options_alter_exercise_taken_by_and_more'),
        ('assessment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.exam'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
    ]
