# Generated by Django 4.2.4 on 2024-04-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_management', '0001_initial'),
        ('curriculum_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.exercise'),
        ),
    ]
