# Generated by Django 4.2.4 on 2024-04-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment_management', '0002_initial'),
        ('user_management', '0001_initial'),
        ('curriculum_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.exam'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
    ]
