# Generated by Django 4.2.4 on 2023-08-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_management', '0001_initial'),
        ('curriculum_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='levels',
            field=models.ManyToManyField(to='school_management.level'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.subject'),
        ),
        migrations.AddField(
            model_name='exercisesubmission',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.exercise'),
        ),
    ]
