# Generated by Django 4.2.4 on 2023-08-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum_management', '0002_initial'),
        ('school_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.classroom'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.subject'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='taken_by',
            field=models.ManyToManyField(through='curriculum_management.ExerciseSubmission', to='user_management.student'),
        ),
    ]
