# Generated by Django 4.2.4 on 2023-08-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_initial'),
        ('user_management', '0003_alter_enrolment_classroom_alter_enrolment_student_and_more'),
        ('assessment_management', '0001_initial'),
        ('curriculum_management', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_score', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_management.level')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum_management.subject')),
                ('taken_by', models.ManyToManyField(through='assessment_management.ExamSubmission', to='user_management.student')),
            ],
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'syllabi'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='taken_by',
            field=models.ManyToManyField(through='assessment_management.ExerciseSubmission', to='user_management.student'),
        ),
        migrations.DeleteModel(
            name='ExerciseSubmission',
        ),
    ]
