# Generated by Django 4.2.4 on 2023-08-23 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_management', '0005_exam_created_at_exam_updated_at_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='taken_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
